[package]
name = "emojicon"
version = "0.1.0"
authors = ["Muhammad Mominul Huque <mominul2082@gmail.com>"]
description = "Convert emoticons B-) into Unicode emoji's 😎"
license = "MIT"
keywords = ["emoji", "emoticon", "unicode", "convert"]
categories = ["text-processing"]
repository = "https://github.com/mominul/emojicon"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
